# Generated by Django 3.1.3 on 2020-11-30 21:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
